import { createReducer } from "../utils";

const initialState = {
	userId: "",
	course_fee: "",
	course: "",
	father_name: "",
	father_occupation: "",
	father_total_exp: "",
	father_exp_with_current_company: "",
	ration_card_number: "",
	annual_income: "",
	loading: false,
	message: "",
	status: "",
};

export default createReducer(initialState, {
	["EDUCATION_LOAN_DATA_VALIDATION_START"]: (state, payload) => ({
		...state,
		userId: payload.userId,
		loading: true,
		status: "In Progress",
	}),
	["EDUCATION_LOAN_DATA_VALIDATION_SUCCESS"]: (state, payload) => ({
		...state,
		course_fee: payload.course_fee,
		course: payload.course,
		father_name: payload.father_name,
		father_occupation: payload.father_occupation,
		father_total_exp: payload.father_total_exp,
		father_exp_with_current_company: payload.father_exp_with_current_company,
		ration_card_number: payload.ration_card_number,
		annual_income: payload.annual_income,
		loading: false,
		message: "Data Validation Successfull",
		status: "Success",
	}),
	["EDUCATION_LOAN_DATA_VALIDATION_FAILED"]: (state, payload) => ({
		...state,
		userId: "",
		course_fee: "",
		course: "",
		father_name: "",
		father_occupation: "",
		father_total_exp: "",
		father_exp_with_current_company: "",
		ration_card_number: "",
		annual_income: "",
		loading: false,
		status: "Failed",
		message: payload,
	}),
	["RESET_DATA"]: (state) => ({
		...state,
		userId: "",
		course_fee: "",
		course: "",
		father_name: "",
		father_occupation: "",
		father_total_exp: "",
		father_exp_with_current_company: "",
		ration_card_number: "",
		annual_income: "",
		loading: false,
		message: "",
		status: "",
	}),
});
