import { createReducer } from "../utils";

const initialState = {
	userId: "",
	loan_type: "",
	loan_amount: "",
	loan_apply_date: "",
	loan_issue_date: "",
	rate_of_interest: "",
	duration_of_loan: "",
	loading: false,
	message: "",
	status: "",
};

export default createReducer(initialState, {
	["LOAN_APPLICATION_DATA_VALIDATION_START"]: (state, payload) => ({
		...state,
		userId: payload.userId,
		loading: true,
		status: "In Progress",
	}),
	["LOAN_APPLICATION_DATA_VALIDATION_SUCCESS"]: (state, payload) => ({
		...state,
		loan_type: payload.loan_type,
		loan_amount: payload.loan_amount,
		loan_apply_date: payload.loan_apply_date,
		loan_issue_date: payload.loan_issue_date,
		rate_of_interest: payload.rate_of_interest,
		duration_of_loan: payload.duration_of_loan,
		loading: false,
		status: "Success",
		message: "Data validation Successful",
	}),
	["LOAN_APPLICATION_DATA_VALIDATION_FAILED"]: (state, payload) => ({
		...state,
		loan_type: "",
		loan_amount: "",
		loan_apply_date: "",
		loan_issue_date: "",
		rate_of_interest: "",
		duration_of_loan: "",
		loading: false,
		status: "Failed",
		message: payload,
	}),
	["RESET_DATA"]: (state) => ({
		...state,
		userId: "",
		loan_type: "",
		loan_amount: "",
		loan_apply_date: "",
		loan_issue_date: "",
		rate_of_interest: "",
		duration_of_loan: "",
		loading: false,
		status: "",
		message: "",
	}),
});
