import { createReducer } from "../utils";

const initialState = {
	userId: "",
	name: "",
	username: "",
	password: "",
	guardian_type: "",
	guardian_name: "",
	address: "",
	citizenship: "",
	state: "",
	country: "",
	gender: "",
	martial_status: "",
	email: "",
	contact: "",
	date_of_birth: "",
	account_type: "",
	branch_name: "",
	loading: false,
	message: "",
	status: "",
};

export default createReducer(initialState, {
	["USER_REGISTRATION_START"]: (state) => ({
		...state,
		loading: true,
		status: "In Progress",
	}),
	["USER_REGISTRATION_SUCCESS"]: (state, payload) => ({
		...state,
		userId: payload.userId,
		name: payload.name,
		username: payload.username,
		password: payload.password,
		guardian_type: payload.guardian_type,
		guardian_name: payload.guardian_name,
		address: payload.address,
		citizenship: payload.citizenship,
		state: payload.state,
		country: payload.country,
		gender: payload.gender,
		martial_status: payload.martial_status,
		email: payload.email,
		contact: payload.contact,
		date_of_birth: payload.date_of_birth,
		account_type: payload.account_type,
		branch_name: payload.branch_name,
		loading: false,
		status: "Success",
		message: "User Registration Successful",
	}),
	["USER_REGISTRATION_FAILED"]: (state, payload) => ({
		...state,
		name: "",
		username: "",
		password: "",
		guardian_type: "",
		guardian_name: "",
		address: "",
		citizenship: "",
		state: "",
		country: "",
		gender: "",
		martial_status: "",
		email: "",
		contact: "",
		date_of_birth: "",
		account_type: "",
		branch_name: "",
		loading: false,
		status: "Failed",
		message: payload,
	}),
	["RESET_DATA"]: (state) => ({
		...state,
		name: "",
		username: "",
		password: "",
		guardian_type: "",
		guardian_name: "",
		address: "",
		citizenship: "",
		state: "",
		country: "",
		gender: "",
		martial_status: "",
		email: "",
		contact: "",
		date_of_birth: "",
		account_type: "",
		branch_name: "",
		loading: false,
		message: "",
		status: "",
	}),
});
